version: salt

services:
  salt:
    build: .
    ports:
      - "1214:8000"
    depends_on:
      salt_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@salt_db:5432/mydb

  salt_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data_salt1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_salt1: