name: The Peter's speech
author: "@alexereh"
description: |
  Великий государь Пётр Алексеевич зашифровал свой указ новейшим методом, дабы враги не прознали о планах его. 
  Использовал он для сего дела не простые методы шифрования, а хитроумный механизм «рандомизации», 
  созданный иноземными мастерами на языке «Rust».

  Да вот беда – не учёл государь, что генератор сей не для тайнописи предназначен был, 
  а для забавы математической. Теперь же нам надлежит указ расшифровать, 
  ибо в нём содержатся важные сведения о грядущих реформах.

  Сможете ли вы разгадать шифр Петра, основанный на предсказуемом генераторе 
  псевдослучайных чисел, и прочесть его тайное послание?

attribution: "Автор [@alexereh](https://t.me/alexereh)"
category: crypto
value: 1000
type: dynamic
extra:
  initial: 1000
  decay: 10
  minimum: 100

flags:
  - {
    type: "static",
    content: "vrnctf{prng_1s_1nt3r3st1ng}"
    }

files:
  - public/task.zip
  - public/words.txt
  - public/encrypted.bin

state: visible
version: "0.1"
