name: "XenReminder"
author: "@m41den"
category: "web"
# Категория будет отображаться на платформе в описании таска. Поддерживается md формат 
description: |
  Постоянно забываете, о чем были совещания? Мечтаете об интеллектуальном напоминальнике, который отправит вам заметку в нужный момент?
  Тогда корпоративное решение XenReminder будет идеально подходить под все ваши нужды! 
  
  (Заметка Ване: продаем людям с деменцией по нескольку раз, как прочтешь удали)
attribution: "Автор [@m41den](https://t.me/m41den)"
value: 1000
type: dynamic # IDK how much it costs

extra:
  initial: 1000
  decay: 10
  minimum: 100

connection_info: "https://xen.tasks.ctf.vrnctf.ru"

# Все способы описать флаг
# flags:
#     # A static case sensitive flag
#     - flag{3xampl3}
#     # A static case sensitive flag created with a dictionary
#     - {
#         type: "static",
#         content: "flag{wat}",
#     }
#     # A static case insensitive flag
#     - {
#         type: "static",
#         content: "flag{wat}",
#         data: "case_insensitive",
#     }
#     # A regex case insensitive flag
#     - {
#         type: "regex",
#         content: "(.*)STUFF(.*)",
#         data: "case_insensitive",
#     }

flags:
  - vrnctf{CTFM4N_D3M3NT14_ASYLUM}

topics:
  - CRON

files:
  - public/backend.zip

# Хинты по умолчанию скрыты, сделайте их заранее, их откроем на половине соревнований на нерешенные таски
# hints:
#     - {
#         content: "This hint costs points",
#         cost: 10
#     }
#     - This hint is free

# hints:
#   - Изучите внимательно код, где-то здесь затаилась отложенная SQL-инъекция. Но как ее стриггерить?

# visible/hidden
state: visible
version: "0.1"

