FROM node:22-alpine AS build

WORKDIR /app

RUN npm i -g pnpm

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN pnpm install

# Copy the source code
COPY frontend/ ./

# Build the app
RUN npm run build

# Production environment
FROM nginx:alpine

# Copy built assets from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Add nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
